// <auto-generated />
using System;
using AttachManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttachManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240723155146_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttachManagement.Core.Entities.Attachment", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_date_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_date_utc");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.HasIndex("category_id");

                    b.ToTable("attachment", (string)null);
                });

            modelBuilder.Entity("AttachManagement.Core.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("title");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("parent_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("AttachManagement.Core.Entities.Attachment", b =>
                {
                    b.HasOne("AttachManagement.Core.Entities.Category", null)
                        .WithMany("_attachments")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttachManagement.Core.Entities.Category", b =>
                {
                    b.HasOne("AttachManagement.Core.Entities.Category", null)
                        .WithMany("_subCategories")
                        .HasForeignKey("parent_id");
                });

            modelBuilder.Entity("AttachManagement.Core.Entities.Category", b =>
                {
                    b.Navigation("_attachments");

                    b.Navigation("_subCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
